

export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";

export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";

export const DETAILS_TODO_LOADING = "DETAILS_TODO_LOADING";
export const DETAILS_TODO_SUCCESS = "DETAILS_TODO_SUCCESS";

export const EDIT_TODO_LOADING = "EDIT_TODO_LOADING";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";